import { SITE_URL } from './localeRoutes';
import { BUSINESS } from './schema';

/** Pflichtangaben für Impressum & Datenschutz (§ 5 TMG, DSGVO). */
export const LEGAL = {
  operatorName: 'Snizhana Aksenchykova',
  tradeName: BUSINESS.name,
  legalFormDe: 'Kleinunternehmen (§ 19 UStG)',
  legalFormRu: 'мелкое предприятие (§ 19 UStG, без НДС)',
  email: 'snezhana.aksenchikova@gmail.com',
  phone: BUSINESS.phone,
  phoneDisplay: '+49 170 1264472',
  street: BUSINESS.address.street,
  postalCode: BUSINESS.address.postalCode,
  city: BUSINESS.address.city,
  region: BUSINESS.address.region,
  country: 'Deutschland',
  vatId: null,
  isSmallBusiness: true,
  profession: 'Nageldesign / Maniküre / Pediküre',
  supervisoryAuthority: null,
  lastUpdatedDe: 'Juni 2026',
  lastUpdatedRu: 'июнь 2026',
  hostingProvider: 'Contabo GmbH',
  hostingAddress: 'Aschauer Straße 32a, 81549 München, Deutschland',
  privacyAuthority: 'Der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg',
  privacyAuthorityAddress: 'Königstraße 10a, 70173 Stuttgart',
  privacyAuthorityUrl: 'https://www.baden-wuerttemberg.datenschutz.de',
  odrPlatformUrl: 'https://ec.europa.eu/consumers/odr',
};

export const getLegalInterpolation = (lang = 'de') => ({
  operatorName: LEGAL.operatorName,
  tradeName: LEGAL.tradeName,
  legalForm: lang === 'ru' ? LEGAL.legalFormRu : LEGAL.legalFormDe,
  email: LEGAL.email,
  phone: LEGAL.phoneDisplay,
  street: LEGAL.street,
  postalCode: LEGAL.postalCode,
  city: LEGAL.city,
  region: LEGAL.region,
  country: LEGAL.country,
  siteUrl: SITE_URL,
  lastUpdated: lang === 'ru' ? LEGAL.lastUpdatedRu : LEGAL.lastUpdatedDe,
  hostingProvider: LEGAL.hostingProvider,
  hostingAddress: LEGAL.hostingAddress,
  privacyAuthority: LEGAL.privacyAuthority,
  privacyAuthorityAddress: LEGAL.privacyAuthorityAddress,
  privacyAuthorityUrl: LEGAL.privacyAuthorityUrl,
  odrPlatformUrl: LEGAL.odrPlatformUrl,
  profession: LEGAL.profession,
  instagram: '@smartnails_stuttgart',
  whatsapp: LEGAL.phoneDisplay,
});
